added sales and dashboard screens
tesler-platform/tesler-demo pull request #68
Opened 2022-05-04 08:13 UTC by DariaMitrofanovna

2022-05-11 13:58 UTC, achabalov commented on ui/src/components/widgets/Funnel/Funnel.tsx
> +        content: data1 => data1.value,
I suggest renaming the data

2022-05-11 14:03 UTC, achabalov commented on ui/src/components/DashboardCard/DashboardCard.module.css
> +@value main-light-mode from colors;
the variable is not used

2022-05-11 14:57 UTC, achabalov requested changes
view comment

2022-05-12 16:30 UTC, DRITE requested changes

2022-05-18 14:51 UTC, DariaMitrofanovna commented on ui/src/components/widgets/Funnel/Funnel.tsx
> +    const funnelData = useMemo(() => sortedData?.map(i => ({ ...i, value: Number.parseInt(i.value, 10) })), [data])
fixed

2022-05-18 14:51 UTC, DariaMitrofanovna commented on ui/src/components/widgets/Funnel/Funnel.tsx
> +        content: data1 => data1.value,
fixed

2022-05-18 14:51 UTC, DariaMitrofanovna commented on ui/src/components/widgets/RingProgress/RingProgress.tsx
> +                    <p className={styles.text3}>{descriptionFieldValue.data}</p>
fixed

2022-05-18 14:51 UTC, DariaMitrofanovna commented on ui/src/components/DashboardCard/DashboardCard.module.css
> +@value main-light-mode from colors;
fixed

2022-05-18 14:51 UTC, DariaMitrofanovna commented on ui/src/components/widgets/RingProgress/RingProgress.tsx
> +    }
fixed

2022-05-18 14:52 UTC, DariaMitrofanovna commented on ui/src/components/widgets/DashboardList/DashboardList.tsx
> +            <h2 className={styles.header}>{meta?.title}</h2>
fixed

2022-05-18 14:52 UTC, DariaMitrofanovna commented on ui/src/components/widgets/RingProgress/RingProgress.module.css
> +  color: #141F35;
fixed

2022-05-18 14:52 UTC, DariaMitrofanovna commented on ui/src/components/widgets/RingProgress/RingProgress.module.css
> +  color: #D9D9D9;
fixed

2022-05-18 14:52 UTC, DariaMitrofanovna commented on ui/src/components/widgets/RingProgress/RingProgress.module.css
> +  max-width: 400px;
fixed

2022-05-18 14:52 UTC, DariaMitrofanovna commented on ui/src/components/widgets/RingProgress/RingProgress.tsx
> +                        }}
fixed

2022-05-18 14:52 UTC, DariaMitrofanovna commented on ui/src/components/widgets/RingProgress/RingProgress.tsx
> +                    <p className={styles.text1}>{text}</p>
fixed

2022-05-18 14:52 UTC, DariaMitrofanovna commented on src/main/resources/meta/widget/dashboard/salesRingProgress.widget.json
> +  "options" : {
fixed

2022-05-18 14:52 UTC, DariaMitrofanovna commented on src/main/resources/meta/widget/dashboard/salesFunnel.widget.json
> +    "dataKey": "salesStatistics",
fixed

2022-05-18 14:53 UTC, DariaMitrofanovna commented on src/main/resources/meta/widget/dashboard/salesRingProgress.widget.json
> +  "bc": "salesRingProgress",
fixed

2022-05-18 14:53 UTC, DariaMitrofanovna commented on ui/src/interfaces/widget.ts
> +}
fixed

2022-05-18 14:53 UTC, DariaMitrofanovna commented on ui/src/components/DashboardCard/DashboardCard.module.css
> +  min-width: 440px;
fixed

2022-05-18 14:53 UTC, merged